### PR TITLE
Fix for IO#read(n) with n > IO::BUF_SIZE

### LINKED ISSUE #87: IO#read(n) blocks although n bytes are readable
Starting with commit 27f422880fa501a16642e0499b8140c074b5269b the `r.read(n)` in the following test blocks indefinitely:

```ruby
assert "large read from an IO" do
  r,w = IO.pipe
  n = 2**15
  w.write 'a'*n
  assert_equal r.read(n), 'a'*n
end
```

The previous commit 3a73a5849388fe908af7131804f9fc7f55472651 evaluates the test without error.

### PR DESCRIPTION
**Pull request by christopheraue**
Fixes #87. The error was caused by not reducing the number of bytes to read from the internal buffer for consecutive iterations of the `while 1` loop inside `IO#read`.

### CODE REVIEW

File: test/io.rb [hunk 1]
```diff
@@ -140,6 +140,13 @@ def assert_nothing_raised(*exp)
   end
 end
 
+assert "IO#read(n) with n > IO::BUF_SIZE" do
+  r,w = IO.pipe
+  n = IO::BUF_SIZE+1
+  w.write 'a'*n
```
Comment (tsahara) [inline test/io.rb]: (Just a comment)

This will block on the systems where the buffer size of pipe is equal to or smaller than `BUF_SIZE` (= 4096).  I found it is 65536 on most OSs (NetBSD/OpenBSD/macOS/Linux(>=2.6.11)) and 8192 on FreeBSD.

**Comment by tsahara** [comment]
I could not found the issue when I reviewed #84.  Thanks!
